package com.nuix.superutilities.misc;

/***
 * Encapsulates information about a term designated as a match result generated by {@link TermExpander}.
 * @author Jason Wells
 *
 */
public class ExpandedTermInfo {
	private String originalTerm = "";
	private String matchedTerm = "";
	private long ocurrences = 0;
	private float similarity = 0.0f;
	
	public String getOriginalTerm() {
		return originalTerm;
	}
	public void setOriginalTerm(String originalTerm) {
		this.originalTerm = originalTerm;
	}
	
	public String getMatchedTerm() {
		return matchedTerm;
	}
	public void setMatchedTerm(String matchedTerm) {
		this.matchedTerm = matchedTerm;
	}
	
	public long getOcurrences() {
		return ocurrences;
	}
	public void setOcurrences(long ocurrences) {
		this.ocurrences = ocurrences;
	}
	
	public float getSimilarity() {
		return similarity;
	}
	public void setSimilarity(float similarity) {
		this.similarity = similarity;
	}
	
	@Override
	public String toString() {
		return "ExpandedTermInfo [originalTerm=" + originalTerm + ", matchedTerm=" + matchedTerm + ", ocurrences="
				+ ocurrences + ", similarity=" + similarity + "]";
	}
}
